version: "3.6"
services:

  mariadb:
    image: mariadb:10.3
    container_name: leanferret-mariadb
    volumes:
      - ./Docker/Config/mariadb/:/etc/mysql/conf.d
      - ./.Data/Docker/Database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=app
      - MYSQL_USER=toor
      - MYSQL_PASSWORD=toor
    ports:
      - "8083:3306"

  webserver:
    image: nginx:alpine
    container_name: leanferret-webserver
    working_dir: /project/app
    volumes:
      - ./App:/project/app:cached
      - ./Docker/Config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"

  php-fpm:
    image: leanferret-php-fpm:${PHP_VERSION}
    build:
      context: ./Docker/Dockerfile/php
      dockerfile: Dockerfile
      args:
        phpversion: ${PHP_VERSION}
    container_name: leanferret-php${PHP_VERSION}-fpm
    working_dir: /project/app
    secrets:
      - id_rsa.pub
      - id_rsa
    volumes:
      - ./App:/project/app:cached
      - ./Docker/Config/php/php.ini:/usr/local/etc/php/php.ini
      - ./Docker/Config/ssh/config:/home/www-data/.ssh/config
      - ~/.composer/cache:/home/www-data/.composer/cache:cached

  node:
    image: leanferret-node:${NODE_VERSION}-alpine
    build:
      context: ./Docker/Dockerfile/node
      dockerfile: Dockerfile
      args:
        nodeversion: ${NODE_VERSION}
    container_name: leanferret-node-${NODE_VERSION}
    working_dir: /project/app
    user: "node"
    volumes:
      - ./App:/project/app:cached
      - ./Docker/Config/node/.yarnrc:/project/.yarnrc
      - node_yarn:/home/node/yarn
    command: "node"

volumes:
  node_yarn:

secrets:
  id_rsa.pub:
    file: ~/.ssh/id_rsa.pub
  id_rsa:
    file: ~/.ssh/id_rsa


  #mailcatcher:
  #  image: schickling/mailcatcher
  #  environment:
  #    - MAILCATCHER_PORT_1025_TCP_ADDR=1025
  #  ports:
  #    - "1080:1080"
  #  links:
  #    - application

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    #container_name: phpmyadmin
#    environment:
#      - PMA_HOST=mariadb
#      - PMA_PORT=3306
#      - PMA_USER=toor
#      - PMA_PASSWORD=toor
#    restart: always
#    ports:
#      - 8082:80
#    volumes:
#      - /sessions

  # see: https://github.com/deviantony/docker-elk
#  elasticsearch:
#    build: Docker/Elk/elasticsearch/
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

#  logstash:
#    build: Docker/Elk/logstash/
#    command: -f /etc/logstash/conf.d/
#    volumes:
#      - ./docker-elk/logstash/config:/etc/logstash/conf.d
#    ports:
#      - "5000:5000"
#    depends_on:
#      - elasticsearch

#  kibana:
#    build: Docker/Elk/kibana/
#    volumes:
#      - ./docker-elk/kibana/config/:/etc/kibana/
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
