version: "3.6"
services:

  mariadb:
    image: mariadb:${VERSION_MARIADB}
    volumes:
      - ${CONF_MARIADB_MYCNF}:/etc/mysql/conf.d/my.cnf
      - ./.Data/Docker/Database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${CRED_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${CRED_MYSQL_DATABASE}
      - MYSQL_USER=${CRED_MYSQL_USER}
      - MYSQL_PASSWORD=${CRED_MYSQL_PASSWORD}
    ports:
      - "${PORT_MARIADB}:3306"

  webserver:
    image: nginx:alpine
    working_dir: /project/app
    volumes:
      - ./App:/project/app:cached
      - ${CONF_NGINX_VHOST}:/etc/nginx/conf.d/default.conf
    ports:
      - "${PORT_NGINX}:80"

  php-fpm:
    image: leanferret-php-fpm:${VERSION_PHP}
    build:
      context: ./Docker/Dockerfile/php
      dockerfile: Dockerfile
      args:
        phpversion: ${VERSION_PHP}
    working_dir: /project/app
    secrets:
      - id_rsa.pub
      - id_rsa
    volumes:
      - ./App:/project/app:cached
      - ${CONF_PHP_PHPINI}:/usr/local/etc/php/php.ini
      - ${CONF_SSH}:/home/www-data/.ssh/config
      - ~/.composer/cache:/home/www-data/.composer/cache:cached

  node:
    image: leanferret-node:${VERSION_NODE}-alpine
    build:
      context: ./Docker/Dockerfile/node
      dockerfile: Dockerfile
      args:
        nodeversion: ${VERSION_NODE}
    working_dir: /project/app
    user: "node"
    volumes:
      - ./App:/project/app:cached
      - ${CONF_NODE_YARNRC}:/project/.yarnrc
      - node_yarn_cache:/home/node/yarn
      - node_modules:/project/app/node_modules
    command: "node"

volumes:
  node_yarn_cache:
  node_modules:

secrets:
  id_rsa.pub:
    file: ~/.ssh/id_rsa.pub
  id_rsa:
    file: ~/.ssh/id_rsa
